logfile = "/opt/al/pkg/al_services/alsvc_comber/event_json.json"
indicatorfile = "/opt/al/pkg/al_services/alsvc_comber/bigfile_json.json"
indicator_dir = "/opt/al/pkg/al_services/alsvc_comber/sysmon/"
alert_document = "/opt/al/pkg/al_services/alsvc_comber/alerts_generated.txt"
event_log = "/opt/al/pkg/al_services/alsvc_comber/sysmonout.xml"
eventlog_empty = "/opt/al/pkg/al_services/alsvc_comber/event_json.json"
yaml_path = "/opt/al/pkg/al_services/alsvc_comber/indicators.yaml"
json_path = "/opt/al/pkg/al_services/alsvc_comber/indicators.json"
