logfile = "/opt/al/pkg/al_services/alsvc_beachcomber/event_json.json"
indicatorfile = "/opt/al/pkg/al_services/alsvc_beachcomber/bigfile_json.json"
indicator_dir = "/opt/al/pkg/al_services/alsvc_beachcomber/sysmon/"
alert_document = "/opt/al/pkg/al_services/alsvc_beachcomber/alerts_generated.txt"
event_log = "/opt/al/pkg/al_services/alsvc_beachcomber/sysmonout.xml"
eventlog_empty = "/opt/al/pkg/al_services/alsvc_beachcomber/event_json.json"
yaml_path = "/opt/al/pkg/al_services/alsvc_beachcomber/indicators.yaml"
json_path = "/opt/al/pkg/al_services/alsvc_beachcomber/indicators.json"
