logfile = "event_json.json"
indicatorfile = "bigfile_json.json"
indicator_dir = "sysmon/"
config_folder = ""
alert_document = "alerts_generated.txt"
event_log = "sysmonout.xml"
eventlog_empty = "event_json.json"

yaml_path = "indicators.yaml"
json_path = "indicators.json"
